[[edge_functions]]
path = "/geolocation"
function = "geolocation"
[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
[[headers]]
for = "/_astro/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
for = "/fonts/*"
[headers.values]
Cache-Control = "public, max-age=31536000"
